name: Pwnies and rainbows and and and...
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://morbidrsa.github.io'
# google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://morbidrsa.github.io'
author:         'Johannes Thumshirn'
github_username: morbidrsa
